language: rust
rust:
  - 1.34.2
  - stable
  - nightly
env:
  matrix:
    - FEATURES=''
    - FEATURES='alloc'
    - FEATURES='std'
jobs:
  exclude:
  - rust: 1.34.2
    env: FEATURES='alloc'

script:
  - if [ "${TRAVIS_RUST_VERSION}" == "1.34.2" ]; then
      cargo build -v --no-default-features --features="$FEATURES";
    else
      cargo test -v --no-default-features --features="$FEATURES";
    fi
