[package]
name = "lzw"
version = "0.10.0"
license = "MIT/Apache-2.0"
description = "LZW compression and decompression."
authors = ["nwin <nwin@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/nwin/lzw.git"

[lib]
bench = false

[dev-dependencies]
criterion = "0.3.1"

[features]
default = ["raii_no_panic"]
raii_no_panic = []

[[bin]]
name = "lzw"
path = "bin/lzw.rs"
bench = false

[[bench]]
name = "msb8"
harness = false
