[package]
name = "weezl"
version = "0.0.1"
license = "MIT/Apache-2.0"
description = "Fast LZW compression and decompression."
authors = ["HeroicKatora <andreas.molzer@gmx.de>"]
readme = "README.md"
repository = "https://github.com/image-rs/lzw.git"

[lib]
name = "weezl"
bench = false

[dev-dependencies]
criterion = "0.3.1"

[features]
default = ["raii_no_panic"]
raii_no_panic = []

[[bin]]
name = "lzw"
path = "bin/lzw.rs"
bench = false

[[bench]]
name = "msb8"
harness = false
